## Several Parameter of pd.read_csv()

In [1]:
import pandas as pd

In [4]:
df1 = pd.read_csv("Fortune_10.csv")
df1.head(5)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%

### Read Only a fixed number of rows from the Dataset

In [6]:
df2 = pd.read_csv("Fortune_10.csv", nrows=3)
df2

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%

### Read Only a fixed number of columns from the Dataset

In [9]:
df3 = pd.read_csv("Fortune_10.csv", usecols=[1,2,3,4])
df3

              Name             Industry  Inception       Revenue
0          Lamtone          IT Services       2009  $11,757,018
1        Stripfind   Financial Services       2010  $12,329,371
2  Canecorporation               Health       2012  $10,597,009
3         Mattouch          IT Services       2013  $14,026,934
4        Techdrill               Health       2009  $10,573,990
5         Techline               Health       2006  $13,898,119
6          Cityace               Health       2010   $9,254,614
7   Kayelectronics               Health       2009   $9,451,943
8          Ganzlax          IT Services       2011  $14,001,180
9      Trantraxlax  Government Services       2011  $11,088,336

### Skips specific rows while reading the dataset

In [14]:
df4 = pd.read_csv("Fortune_10.csv", skiprows = 3)
df4.head(3)

,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
0,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
1,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
2,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%

### Sets one column as the DataFrame index

In [15]:
df5 = pd.read_csv("Fortune_10.csv", index_col= 0)
df5.head(4)

,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%

### Specifies which row contains column names

In [17]:
df6 = pd.read_csv("Fortune_10.csv", header= 5)
df6.head(5)

,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
0,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
1,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
2,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
3,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
4,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

### Allocate Custom column names

In [20]:
df7 = pd.read_csv("Fortune_10.csv", names=[1,2,3,4,5,6,7,8,9])
df7.head(5)

,1,2,3,4,5,6,7,8,9
0,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth,NaN
1,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%,NaN
2,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%,NaN
3,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%,NaN
4,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%,NaN