## Pandas NAN value drop
    In Pandas, NaN (Not a Number) represents missing or undefined values in a dataset.
    The Function dropna() method to remove rows or columns containing NaN values, helping you prepare clean and reliable datasets.
    
        Key Parameters :
            - axis=0	: Drops rows (default behavior)
            - axis=1	: Drops columns
            - how='all'	: Drops only if all values are NaN
            - how='any'	: Drops if any NaN is present (default)
            - thresh=2	: Keeps rows/columns with at least 2 non-null values
            - subset	: Drops NaN based on specific columns only
            - inplace=False	: Returns a new DataFrame (default)
            - inplace=True	: Modifies the original DataFrame

In [34]:
import pandas as pd
import numpy as np

In [35]:
df1 = pd.read_csv("Fortune_5.csv")
df1

    ID             Name           Companies      Profit Growth
0  1.0          Lamtone         IT Services   5274553.0    30%
1  2.0        Stripfind  Financial Services  11412916.0    20%
2  3.0  Canecorporation              Health   3005820.0     7%
3  4.0              NaN         IT Services   6597557.0    NaN
4  5.0             Mark                 NaN   3138627.0    21%
5  NaN              NaN                 NaN         NaN    NaN
6  NaN              NaN                 NaN         NaN    NaN
7  NaN              NaN                 NaN         NaN    NaN
8  NaN              NaN                 NaN         NaN    NaN
9  NaN              NaN                 NaN         NaN    NaN

### Extract null value in true/false format

In [36]:
df2 = pd.read_csv("Fortune_10.csv")

In [37]:
df2.isnull().any()

ID           False
Name         False
Industry     False
Inception    False
Revenue      False
Expenses      True
Profit       False
Growth       False
dtype: bool

### Extract Exact number of null value in Dataset

In [38]:
df1.isnull().sum()

ID           5
Name         6
Companies    6
Profit       5
Growth       6
dtype: int64

### Total Number of null value

In [39]:
print ("Total Null Value in Dataset ;",[(df1.isnull().sum().sum())])

Total Null Value in Dataset ; [np.int64(28)]

### Extract not null Values

In [40]:
df2.notnull().sum()

ID           10
Name         10
Industry     10
Inception    10
Revenue      10
Expenses      9
Profit       10
Growth       10
dtype: int64

### Total Number of not null values

In [41]:
print ("Total Not Null Value in Dataset ;",[(df2.notnull().sum().sum())])

Total Not Null Value in Dataset ; [np.int64(79)]

### For droping the nan values

In [42]:
df2.dropna()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

### Droping NAN Values by Column

In [43]:
df2.dropna(axis = 1)

,ID,Name,Industry,Inception,Revenue,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990",3138627,8%
5,6,Techline,Health,2006,"$13,898,119",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336",5453060,7%

### If a rows has complete NAN all feature

In [44]:
df1.dropna(how = 'all')

    ID             Name           Companies      Profit Growth
0  1.0          Lamtone         IT Services   5274553.0    30%
1  2.0        Stripfind  Financial Services  11412916.0    20%
2  3.0  Canecorporation              Health   3005820.0     7%
3  4.0              NaN         IT Services   6597557.0    NaN
4  5.0             Mark                 NaN   3138627.0    21%

### If a rows has Atleast One NAN all Feature

In [45]:
df1.dropna(how = 'any')

    ID             Name           Companies      Profit Growth
0  1.0          Lamtone         IT Services   5274553.0    30%
1  2.0        Stripfind  Financial Services  11412916.0    20%
2  3.0  Canecorporation              Health   3005820.0     7%

In [46]:
df1.dropna(thresh = 4)

    ID             Name           Companies      Profit Growth
0  1.0          Lamtone         IT Services   5274553.0    30%
1  2.0        Stripfind  Financial Services  11412916.0    20%
2  3.0  Canecorporation              Health   3005820.0     7%
4  5.0             Mark                 NaN   3138627.0    21%

### Drop the NAN Value from the Selected Column

In [47]:
df1.dropna(subset = ['Profit','Growth'], inplace = True)
df1.isnull().sum()

ID           0
Name         0
Companies    1
Profit       0
Growth       0
dtype: int64

In [48]:
df1.fillna({'Expense' : '123'})

    ID             Name           Companies      Profit Growth
0  1.0          Lamtone         IT Services   5274553.0    30%
1  2.0        Stripfind  Financial Services  11412916.0    20%
2  3.0  Canecorporation              Health   3005820.0     7%
4  5.0             Mark                 NaN   3138627.0    21%