## Fill NAN Value
        Filling NaN (Missing) Values in Pandas
        In Pandas, NaN (Not a Number) represents missing or undefined data.
        Pandas provides flexible methods to fill NaN values using constants (like 0 or "Unknown"), statistical measures (mean, median, mode), or forward/backward propagation
        
        Most Common Way to Fill NAN Value 
         - ffill -> Fill NAN Values with Forward values
         - bfill -> Fill NAN values with Previous Values
         - etc

In [3]:
import pandas as pd

In [5]:
df1 = pd.read_csv("Fortune_10-1.csv")
df1

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,NaN,2009,"$10,573,990","7,435,363 Dollars",3138627,NaN
5,6,Techline,NaN,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7,Cityace,NaN,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8,Kayelectronics,NaN,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

### Fill The NAN Value By Dictionary

In [8]:
df1.fillna({'Industry':'None','Expenses':'None','Growth':'None'})

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,None
4,5,Techdrill,None,2009,"$10,573,990","7,435,363 Dollars",3138627,None
5,6,Techline,None,2006,"$13,898,119","5,470,303 Dollars",8427816,None
6,7,Cityace,None,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8,Kayelectronics,None,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",None,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

### Fill NAN by method - ffill

In [16]:
df1.fillna(method = 'ffill', limit = 1,inplace = True)
df1

C:\Users\HP\AppData\Local\Temp\ipykernel_12936\2995714876.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method = 'ffill', limit = 1,inplace = True)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,5,Techdrill,IT Services,2009,"$10,573,990","7,435,363 Dollars",3138627,7%
5,6,Techline,IT Services,2006,"$13,898,119","5,470,303 Dollars",8427816,7%
6,7,Cityace,IT Services,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8,Kayelectronics,IT Services,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

### Fill NAN by method - bfill

In [18]:
df1.fillna(method = 'bfill',inplace = False)
df1

C:\Users\HP\AppData\Local\Temp\ipykernel_12936\3817703551.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method = 'bfill',inplace = False)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,5,Techdrill,IT Services,2009,"$10,573,990","7,435,363 Dollars",3138627,7%
5,6,Techline,IT Services,2006,"$13,898,119","5,470,303 Dollars",8427816,7%
6,7,Cityace,IT Services,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8,Kayelectronics,IT Services,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%