## Handling Missing Value By - Interpolate() Function
     In pandas, Missing values are a common issue in real-world datasets and can negatively affect data analysis and model performance.
    The interpolate() function in Pandas provides an effective way to fill missing values by estimating them from existing data points.
    Uses various interpolation techniques

In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv('student_result1.csv')
df1

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

### Using interpolation function

In [6]:
df1.interpolate()

C:\Users\HP\AppData\Local\Temp\ipykernel_10544\1134058721.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df1.interpolate()

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

### Using interpolate method - "index"

In [7]:
df1.interpolate(method = 'index')

C:\Users\HP\AppData\Local\Temp\ipykernel_10544\1781550022.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df1.interpolate(method = 'index')

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

### Using interpolate method - "Linear"

In [8]:
df1.interpolate(method = 'linear')

C:\Users\HP\AppData\Local\Temp\ipykernel_10544\2031788591.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df1.interpolate(method = 'linear')

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

### Using interpolate method - "Time"

In [10]:
# Note : one of the col. should be in time - date dtype
df1 = pd.read_csv('student_result1.csv', index_col = 'Student ID')
df1

           Section  Class  Study hrs  Social Media usage hrs  Percentage
Student ID
1001             A     10          2                       3          50
1002             B     10          6                       2          80
1003             A     10          3                       2          60
1004             C     11          0                       1          45
1005             C     12          5                       2          75

### Using axis Parameter

In [13]:
df1.interpolate(axis = 0)

C:\Users\HP\AppData\Local\Temp\ipykernel_10544\3565005860.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df1.interpolate(axis = 0)

           Section  Class  Study hrs  Social Media usage hrs  Percentage
Student ID
1001             A     10          2                       3          50
1002             B     10          6                       2          80
1003             A     10          3                       2          60
1004             C     11          0                       1          45
1005             C     12          5                       2          75