## Pandas Melt Function :
    The melt() function in Pandas is used to reshape a DataFrame from wide format to long format.
    It's making the data easier to analyze, visualize, and aggregate.
   - It converts multiple columns into two columns.
   - one for column names and one for values.

In [2]:
import pandas as pd

In [16]:
df1 = pd.read_csv('Fortune_10-1.csv')
df1.head(5)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,NaN,2009,"$10,573,990","7,435,363 Dollars",3138627,NaN

### Basic Melt (Global Unpivot)

In [17]:
# Without parameters, melt() unpivots ALL columns into 'variable' and 'value'
# This results in a very long DataFrame where every cell from the original table has its own row
pd.melt(df1)

   variable value
0        ID     1
1        ID     2
2        ID     3
3        ID     4
4        ID     5
..      ...   ...
75   Growth   NaN
76   Growth   16%
77   Growth    4%
78   Growth   18%
79   Growth    7%

[80 rows x 2 columns]

### Melting with Identifier Variables

In [18]:
# Use 'id_vars' to keep specific columns fixed (unmelted)
# Here, 'Name' and 'Revenue' stay as columns
pd.melt(df1,
       id_vars=['Name','Revenue']
       )

               Name       Revenue   variable                value
0           Lamtone  $11,757,018          ID                    1
1         Stripfind  $12,329,371          ID                    2
2   Canecorporation  $10,597,009          ID                    3
3          Mattouch  $14,026,934          ID                    4
4         Techdrill  $10,573,990          ID                    5
5          Techline  $13,898,119          ID                    6
6           Cityace   $9,254,614          ID                    7
7    Kayelectronics   $9,451,943          ID                    8
8           Ganzlax  $14,001,180          ID                    9
9       Trantraxlax  $11,088,336          ID                   10
10          Lamtone  $11,757,018    Industry          IT Services
11        Stripfind  $12,329,371    Industry   Financial Services
12  Canecorporation  $10,597,009    Industry               Health
13         Mattouch  $14,026,934    Industry          IT Services
14        Techdrill  $10,573,990    Industry                  NaN
15         Techline  $13,898,119    Industry                  NaN
16          Cityace   $9,254,614    Industry                  NaN
17   Kayelectronics   $9,451,943    Industry                  NaN
18          Ganzlax  $14,001,180    Industry          IT Services
19      Trantraxlax  $11,088,336    Industry  Government Services
20          Lamtone  $11,757,018   Inception                 2009
21        Stripfind  $12,329,371   Inception                 2010
22  Canecorporation  $10,597,009   Inception                 2012
23         Mattouch  $14,026,934   Inception                 2013
24        Techdrill  $10,573,990   Inception                 2009
25         Techline  $13,898,119   Inception                 2006
26          Cityace   $9,254,614   Inception                 2010
27   Kayelectronics   $9,451,943   Inception                 2009
28          Ganzlax  $14,001,180   Inception                 2011
29      Trantraxlax  $11,088,336   Inception                 2011
30          Lamtone  $11,757,018    Expenses    6,482,465 Dollars
31        Stripfind  $12,329,371    Expenses      916,455 Dollars
32  Canecorporation  $10,597,009    Expenses    7,591,189 Dollars
33         Mattouch  $14,026,934    Expenses    7,429,377 Dollars
34        Techdrill  $10,573,990    Expenses    7,435,363 Dollars
35         Techline  $13,898,119    Expenses    5,470,303 Dollars
36          Cityace   $9,254,614    Expenses    6,249,498 Dollars
37   Kayelectronics   $9,451,943    Expenses    3,878,113 Dollars
38          Ganzlax  $14,001,180    Expenses                  NaN
39      Trantraxlax  $11,088,336    Expenses    5,635,276 Dollars
40          Lamtone  $11,757,018      Profit              5274553
41        Stripfind  $12,329,371      Profit             11412916
42  Canecorporation  $10,597,009      Profit              3005820
43         Mattouch  $14,026,934      Profit              6597557
44        Techdrill  $10,573,990      Profit              3138627
45         Techline  $13,898,119      Profit              8427816
46          Cityace   $9,254,614      Profit              3005116
47   Kayelectronics   $9,451,943      Profit              5573830
48          Ganzlax  $14,001,180      Profit             11901180
49      Trantraxlax  $11,088,336      Profit              5453060
50          Lamtone  $11,757,018      Growth                  30%
51        Stripfind  $12,329,371      Growth                  20%
52  Canecorporation  $10,597,009      Growth                   7%
53         Mattouch  $14,026,934      Growth                  NaN
54        Techdrill  $10,573,990      Growth                  NaN
55         Techline  $13,898,119      Growth                  NaN
56          Cityace   $9,254,614      Growth                  16%
57   Kayelectronics   $9,451,943      Growth                   4%
58          Ganzlax  $14,001,180      Growth                  18%
59      Trantraxlax  $11,088,336      Growth                   7%

### Targeted Unpivoting with Custom Names

In [20]:
# 'id_vars': Columns to keep as identifiers
# 'value_vars': Specific columns you want to unpivot (if omitted, all non-id_vars are used)
# 'var_name': Custom header for the new 'variable' column
# 'value_name': Custom header for the new 'value' column

pd.melt(
    df1,
    id_vars=['Name','Revenue'],
    value_vars=['Industry'],
    var_name='Category',
    value_name='Data'
)

              Name       Revenue  Category                 Data
0          Lamtone  $11,757,018   Industry          IT Services
1        Stripfind  $12,329,371   Industry   Financial Services
2  Canecorporation  $10,597,009   Industry               Health
3         Mattouch  $14,026,934   Industry          IT Services
4        Techdrill  $10,573,990   Industry                  NaN
5         Techline  $13,898,119   Industry                  NaN
6          Cityace   $9,254,614   Industry                  NaN
7   Kayelectronics   $9,451,943   Industry                  NaN
8          Ganzlax  $14,001,180   Industry          IT Services
9      Trantraxlax  $11,088,336   Industry  Government Services