## Pandas Merge Function
    In Pandas, merging is used to join two or more DataFrames into one based on common data columns.By using merge operations, we can connect related data efficiently and create meaningful insights.
     It works similar to SQL joins and helps organize and analyze data that is stored in separate tables.

In [30]:
import pandas as pd

## -> Basic Merging

### Creating two sample DataFrames with a common 'ID' column

In [31]:
df1 = pd.DataFrame({'ID': [1,2,3,4,5],'Class_no': [101,102,103,104,105]})
df2 = pd.DataFrame({'ID': [1,2,3,4,5], 'Class_Teacher': ['Nilesh Sir', 'Swapna Mam', 'Rahul Sir', 'Megha Mam', 'Nitu Mam']})

In [32]:
# Merging the two DataFrames; it automatically finds the common column 'ID'
df3 = pd.merge(df1,df2)
df3

   ID  Class_no Class_Teacher
0   1       101    Nilesh Sir
1   2       102    Swapna Mam
2   3       103     Rahul Sir
3   4       104     Megha Mam
4   5       105      Nitu Mam

In [33]:
# Explicitly specifying the 'on' parameter to merge on the 'ID' column
df3 = pd.merge(df1,df2, on ='ID')
df3

   ID  Class_no Class_Teacher
0   1       101    Nilesh Sir
1   2       102    Swapna Mam
2   3       103     Rahul Sir
3   4       104     Megha Mam
4   5       105      Nitu Mam

## -> Merging using other parameters

In [34]:
df1 = pd.DataFrame({'ID': [1,2,3,4,5],'Class_no': [101,102,103,104,105]})
df2 = pd.DataFrame({'ID': [1,2,3,6,7], 'Class_Teacher': ['Nilesh Sir', 'Swapna Mam', 'Rahul Sir', 'Megha Mam', 'Nitu Mam']})

In [35]:
# Inner Join (default): Keeps only rows with IDs present in both DataFrames
df3 = pd.merge(df1,df2) # By default how = 'inner'
df3

   ID  Class_no Class_Teacher
0   1       101    Nilesh Sir
1   2       102    Swapna Mam
2   3       103     Rahul Sir

In [36]:
# Left Join: Keeps all records from the left table (df_1), adding NaNs where matches are missing
df3 = pd.merge(df1,df2,how = 'left')  # Give complete record of left side table
df3

   ID  Class_no Class_Teacher
0   1       101    Nilesh Sir
1   2       102    Swapna Mam
2   3       103     Rahul Sir
3   4       104           NaN
4   5       105           NaN

In [37]:
# Right Join: Keeps all records from the right table (df_2)
df3 = pd.merge(df1,df2,how = 'right')  # Give complete record of right side table
df3

   ID  Class_no Class_Teacher
0   1     101.0    Nilesh Sir
1   2     102.0    Swapna Mam
2   3     103.0     Rahul Sir
3   6       NaN     Megha Mam
4   7       NaN      Nitu Mam

In [38]:
# Outer Join: Keeps all records from both tables, filling missing data with NaN
df3 = pd.merge(df1,df2,how = 'outer')  # Give complete record of both side table
df3

   ID  Class_no Class_Teacher
0   1     101.0    Nilesh Sir
1   2     102.0    Swapna Mam
2   3     103.0     Rahul Sir
3   4     104.0           NaN
4   5     105.0           NaN
5   6       NaN     Megha Mam
6   7       NaN      Nitu Mam

In [39]:
# indicator function ()
df3 = pd.merge(df1,df2,how = 'outer', indicator = False)  
df3

   ID  Class_no Class_Teacher
0   1     101.0    Nilesh Sir
1   2     102.0    Swapna Mam
2   3     103.0     Rahul Sir
3   4     104.0           NaN
4   5     105.0           NaN
5   6       NaN     Megha Mam
6   7       NaN      Nitu Mam

In [40]:
# Using 'indicator=True' to show which table (left, right, or both) the record originated from
df3 = pd.merge(df1,df2,how = 'outer', indicator = True)  # Indicate which record is where
df3

   ID  Class_no Class_Teacher      _merge
0   1     101.0    Nilesh Sir        both
1   2     102.0    Swapna Mam        both
2   3     103.0     Rahul Sir        both
3   4     104.0           NaN   left_only
4   5     105.0           NaN   left_only
5   6       NaN     Megha Mam  right_only
6   7       NaN      Nitu Mam  right_only

In [41]:
# Merging based on the index of the DataFrames and adding suffixes to overlapping column names
df3 = pd.merge(df1, df2, left_index = True, right_index = True, suffixes = ['_Table_1', '_Table_2']) 
df3

   ID_Table_1  Class_no  ID_Table_2 Class_Teacher
0           1       101           1    Nilesh Sir
1           2       102           2    Swapna Mam
2           3       103           3     Rahul Sir
3           4       104           6     Megha Mam
4           5       105           7      Nitu Mam