## Pandas concate() and join () Function
    In Pandas, the concat() function is used to combine two or more DataFrames or Series into a single DataFrame.It helps when you want to:
        -Combine multiple datasets
        -Append rows from one DataFrame to another
        -Add columns from different DataFrames
        -Merge data collected from different files (like CSV files
    The join() function in Pandas is used to combine two DataFrames based on their index or a key column.
        -other → The DataFrame to join
        -on → Column to join on (if not joining on index)
        -how → Type of join
        -'left' (default)
        -'right'
        -'inner'
        -'outer'
        -lsuffix / rsuffix → Suffix for overlapping column names

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([201,202,203,204,205])
s3 = pd.Series([s1,s2])
s3

0      0    1
1    2
2    3
3    4
4    5
dtype: int64
1    0    201
1    202
2    203
3    204
4    205
d...
dtype: object

In [3]:
df1 = pd.DataFrame({'ID' : [1,2,3,4,5],
                    'Name': ['Anil','Sunil','Raju','Rakhi','Ravi'],
                    'Class': [5,6,7,8,9]})

df2 = pd.DataFrame({'ID' : [5,6,7,8],
                    'Name' : ['Sunny','Manoj','Jack','Yash'],
                    'Class': [9,10,11,12]})

df3 = pd.concat([df1,df2])
df3

   ID   Name  Class
0   1   Anil      5
1   2  Sunil      6
2   3   Raju      7
3   4  Rakhi      8
4   5   Ravi      9
0   5  Sunny      9
1   6  Manoj     10
2   7   Jack     11
3   8   Yash     12

### Concate the DataFrame By col.wise with [axis = 1]

In [4]:
df3 = pd.concat([df1,df2],axis = 1)
df3

   ID   Name  Class   ID   Name  Class
0   1   Anil      5  5.0  Sunny    9.0
1   2  Sunil      6  6.0  Manoj   10.0
2   3   Raju      7  7.0   Jack   11.0
3   4  Rakhi      8  8.0   Yash   12.0
4   5   Ravi      9  NaN    NaN    NaN

### For Proper index in DF

In [5]:
df3 = pd.concat([df1,df2], ignore_index = True)
df3

   ID   Name  Class
0   1   Anil      5
1   2  Sunil      6
2   3   Raju      7
3   4  Rakhi      8
4   5   Ravi      9
5   5  Sunny      9
6   6  Manoj     10
7   7   Jack     11
8   8   Yash     12

In [6]:
df3 = pd.concat([df1,df2],axis = 1, join = 'inner')
df3

   ID   Name  Class  ID   Name  Class
0   1   Anil      5   5  Sunny      9
1   2  Sunil      6   6  Manoj     10
2   3   Raju      7   7   Jack     11
3   4  Rakhi      8   8   Yash     12

### Split Data in Two Tables

In [7]:
df3 = pd.concat([df1,df2],axis = 1, keys = ['Table-1','Table-2'])
df3

  Table-1              Table-2
       ID   Name Class      ID   Name Class
0       1   Anil     5     5.0  Sunny   9.0
1       2  Sunil     6     6.0  Manoj  10.0
2       3   Raju     7     7.0   Jack  11.0
3       4  Rakhi     8     8.0   Yash  12.0
4       5   Ravi     9     NaN    NaN   NaN

### Added New Table

In [9]:
df_m = pd.DataFrame({'Marks' : [78,98,89,88,53,90,37,66]})
df4 = pd.concat([df1,df_m], ignore_index = True)
df4

     ID   Name  Class  Marks
0   1.0   Anil    5.0    NaN
1   2.0  Sunil    6.0    NaN
2   3.0   Raju    7.0    NaN
3   4.0  Rakhi    8.0    NaN
4   5.0   Ravi    9.0    NaN
5   NaN    NaN    NaN   78.0
6   NaN    NaN    NaN   98.0
7   NaN    NaN    NaN   89.0
8   NaN    NaN    NaN   88.0
9   NaN    NaN    NaN   53.0
10  NaN    NaN    NaN   90.0
11  NaN    NaN    NaN   37.0
12  NaN    NaN    NaN   66.0

### Record of non value

In [11]:
df5 = df1.join(df_m, how = 'inner')
df5

   ID   Name  Class  Marks
0   1   Anil      5     78
1   2  Sunil      6     98
2   3   Raju      7     89
3   4  Rakhi      8     88
4   5   Ravi      9     53

### Record with All Nan Value

In [12]:
df6 = df1.join(df_m, how = 'outer')
df6

    ID   Name  Class  Marks
0  1.0   Anil    5.0     78
1  2.0  Sunil    6.0     98
2  3.0   Raju    7.0     89
3  4.0  Rakhi    8.0     88
4  5.0   Ravi    9.0     53
5  NaN    NaN    NaN     90
6  NaN    NaN    NaN     37
7  NaN    NaN    NaN     66

In [17]:
df7 = df1.join(df_m, rsuffix = '3')
df7

   ID   Name  Class  Marks
0   1   Anil      5     78
1   2  Sunil      6     98
2   3   Raju      7     89
3   4  Rakhi      8     88
4   5   Ravi      9     53