## Pandas loc and iloc for accessing rows
    In Pandas, loc and iloc are used to select rows and columns from a DataFrame.
    They are two of the most important indexing methods in data analysis.

    - Use loc when you know the row/column name
    - Use iloc when you know the row/column position number

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('student_result1.csv')
df1

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60
3        1004       C     11          0                       1          45
4        1005       C     12          5                       2          75

### 1. Using loc Function

###  For accessing rows

In [7]:
df1.loc[2]

Student ID                1003
Section                      A
Class                       10
Study hrs                    3
Social Media usage hrs       2
Percentage                  60
Name: 2, dtype: object

### Access Record as field set

In [10]:
df1.loc[[4]]

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
4        1005       C     12          5                       2          75

###  Accessing multiple rows

In [11]:
df1.loc[0:3]

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80
2        1003       A     10          3                       2          60
3        1004       C     11          0                       1          45

### For accessing multiple selected record

In [12]:
df1.loc[[0,2,4]]

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
2        1003       A     10          3                       2          60
4        1005       C     12          5                       2          75

### For accessing multiple selected record with selected multiple col

In [13]:
df1.loc[2:4,['Student ID', 'Study hrs']]

   Student ID  Study hrs
2        1003          3
3        1004          0
4        1005          5

###  Getting Records by condition

In [14]:
df1.loc[df1['Percentage']>=70]

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
1        1002       B     10          6                       2          80
4        1005       C     12          5                       2          75

### 2. Using iloc

In [15]:
df1.iloc[3]

Student ID                1004
Section                      C
Class                       11
Study hrs                    0
Social Media usage hrs       1
Percentage                  45
Name: 3, dtype: object

### Access record as field Set

In [18]:
df1.iloc[[3]]

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
3        1004       C     11          0                       1          45

### Accessing multiple rows

In [19]:
df1.iloc[0:2]

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
1        1002       B     10          6                       2          80

### For Accessing multiple seleted record

In [20]:
df1.iloc[[0, 2,4]]

   Student ID Section  Class  Study hrs  Social Media usage hrs  Percentage
0        1001       A     10          2                       3          50
2        1003       A     10          3                       2          60
4        1005       C     12          5                       2          75